# Site settings
title: While True, Continue
email: ldmoray@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Thoughts on software development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ldmoray.github.io" # the base hostname & protocol for your site
twitter_username: ldmoray
github_username:  ldmoray

# Build settings
markdown: kramdown
